import assert from 'node:assert/strict';
import {ImageSize} from '../../image_browser/web/static/state.js';

export async function run(browser, fixtures) {
    const {call, evaluate, waitFor, open, click, imageIs, key, nativeKey, wheel, screenshot, readyImage, pause, position, viewerUrl, presentation, setZoom, headerPositions, requests} = browser;
    const {absoluteRoot, first, second, last} = fixtures;
    await browser.start();
    await waitFor("document.querySelectorAll('.card').length > 5");
    const folderModeAction = await evaluate("document.getElementById('read-strip').getBoundingClientRect().toJSON()");
    const folderActions = await evaluate("document.querySelector('.sort-controls').getBoundingClientRect().toJSON()");
    const folderHeaderHeight = await evaluate("document.querySelector('.app-header').offsetHeight");
    assert.ok(await evaluate("(() => {const buttons=document.querySelector('.browse-controls').getBoundingClientRect(), filter=document.getElementById('filter').getBoundingClientRect(); return buttons.left===16 && buttons.right < filter.left && buttons.top===filter.top && buttons.height===32 && filter.height===32;})()"), 'Layout controls sit left of the filter in one compact row');
    // The layout choice keeps the header geometry fixed and survives history and reload.
    await open(viewerUrl(first));
    await readyImage(first);
    const initialPositions = await headerPositions();
    await presentation('single');
    assert.equal(await evaluate("new URLSearchParams(location.search).get('view')"), 'single');
    assert.ok(await evaluate("document.getElementById('viewer-strip').hidden && document.getElementById('viewer-image').dataset.path === 'Album/Chapter 1/page2.jpg'"));
    assert.deepEqual(await headerPositions(), initialPositions);
    assert.equal(await evaluate("document.getElementById('viewer-canvas').getBoundingClientRect().bottom"), await evaluate('innerHeight'), 'Image-only canvas uses all space below the header');
    assert.equal(await evaluate("getComputedStyle(document.querySelector('.viewer-feedback')).display"), 'none', 'Empty feedback takes no space');
    await call('Page.reload');
    await readyImage(first);
    assert.equal(await evaluate("document.querySelector('[data-reading-layout=strip]').getAttribute('aria-current')"), 'false');
    await key('t');
    await waitFor("!new URLSearchParams(location.search).has('view') && !document.getElementById('viewer-strip').hidden");
    assert.deepEqual(await headerPositions(), initialPositions);
    await click('overview-folder');
    await waitFor("!document.getElementById('overview').hidden");
    assert.equal(await evaluate("new URLSearchParams(location.search).get('view')"), 'grid');
    assert.ok(await evaluate("document.querySelector('.viewer-tools').classList.contains('unavailable')"));
    assert.deepEqual(await headerPositions(), initialPositions);
    await evaluate('history.back()');
    await waitFor("document.querySelector('[data-reading-layout=strip]').getAttribute('aria-current') === 'page' && !document.getElementById('viewer-strip').hidden");
    await readyImage(first);

    // Fit page never upscales a small photo. Native wheel events turn fitted pages.
    await open(viewerUrl('root2.jpg', ImageSize.DEFAULT, ''));
    await readyImage('root2.jpg');
    assert.ok(await evaluate("document.getElementById('viewer-image').width <= 320"));
    await call('Input.dispatchMouseEvent', {type:'mouseWheel', x:700,y:350,deltaX:0,deltaY:120});
    await readyImage('root3.jpg');
    await open(viewerUrl(first));
    await readyImage(first);
    await browser.openInfo();
    await evaluate("Object.defineProperty(navigator, 'clipboard', {configurable:true, value:undefined}); window.originalExecCommand=document.execCommand; document.execCommand=command => { if(command==='copy') { window.copiedPath=document.querySelector('.clipboard-input').value; return true; } return false; }; document.querySelector('#metadata-panel .copy-path').click()");
    await waitFor("window.copiedPath");
    assert.equal(await evaluate('window.copiedPath'), absoluteRoot + '/' + first);
    await evaluate('document.execCommand=window.originalExecCommand');
    assert.equal(await evaluate("getComputedStyle(document.querySelector('#viewer-strip button.selected')).borderColor"), await evaluate("getComputedStyle(document.getElementById('layout-previews')).borderColor"), 'Current thumbnails and layout choices share the selection accent');
    const viewAction = await evaluate("document.getElementById('read-strip').getBoundingClientRect().toJSON()");
    assert.deepEqual(viewAction, folderModeAction, 'View has identical geometry on every screen');
    assert.equal(await evaluate("document.getElementById('browse-folder').getBoundingClientRect().width"), 32);
    assert.equal(folderModeAction.width, 40, 'The primary View action has a wider target');
    assert.ok(await evaluate("[...document.querySelectorAll('.viewer-nav')].every(button => button.textContent.trim()==='' && button.querySelector('svg') && button.getAttribute('aria-label') && button.title && button.getBoundingClientRect().height >= 60)"), 'Navigation has no visible labels and keeps generous click targets');
    const viewerFrame = await evaluate("({header:document.querySelector('.app-header').offsetHeight, canvas:document.getElementById('viewer-canvas').getBoundingClientRect().toJSON()})");
    assert.equal(viewerFrame.header, folderHeaderHeight, 'Image and folder headers have the same height');
    assert.ok(viewerFrame.header <= 45, 'Desktop header uses one compact row');
    assert.equal(viewerFrame.canvas.y, viewerFrame.header, 'Canvas starts immediately below the header');
    assert.equal(await evaluate("document.getElementById('viewer-stage').getBoundingClientRect().bottom"), await evaluate("document.querySelector('.strip-frame').getBoundingClientRect().top"), 'No footer reserves image space');
    assert.ok(await evaluate("document.querySelector('.toolbar').hidden"), 'The shared workspace gives all remaining space to the image');
    // Clicking a detail uses the same numeric zoom and preserves the clicked source point.
    const fitted = await evaluate("document.getElementById('viewer-image').getBoundingClientRect().toJSON()");
    for (const type of ['mousePressed', 'mouseReleased']) await call('Input.dispatchMouseEvent', {type,
        x:fitted.x+fitted.width/2, y:fitted.y+fitted.height*2/3, button:'left', clickCount:1});
    assert.equal(await evaluate("(new URLSearchParams(location.search).get('size') || 'auto')"), '1');
    assert.ok(await evaluate("(() => { const c=document.getElementById('viewer-canvas'), i=document.getElementById('viewer-image'), r=i.getBoundingClientRect(); return Math.abs((c.getBoundingClientRect().top+c.clientHeight/2-r.top)/(r.height/i.naturalHeight)-1200)<3; })()"));
    const canvasBounds = await evaluate("document.getElementById('viewer-canvas').getBoundingClientRect().toJSON()");
    for (const type of ['mousePressed', 'mouseReleased']) await call('Input.dispatchMouseEvent', {type,
        x:canvasBounds.x+canvasBounds.width/2, y:canvasBounds.y+canvasBounds.height/2, button:'left', clickCount:1});
    assert.equal(await evaluate("(new URLSearchParams(location.search).get('size') || 'auto')"), 'auto');
    await click('viewer-zoom-in');
    for (const type of ['mousePressed', 'mouseReleased']) await call('Input.dispatchMouseEvent', {type,
        x:canvasBounds.x+canvasBounds.width/2, y:canvasBounds.y+canvasBounds.height/2, button:'left', clickCount:1});
    assert.equal(await evaluate("(new URLSearchParams(location.search).get('size') || 'auto')"), 'auto', 'Image click returns adjusted zoom to the presentation default');
    assert.deepEqual(await headerPositions(), initialPositions, 'Click zoom does not move header controls');
    assert.deepEqual(await evaluate("document.querySelector('.sort-controls').getBoundingClientRect().toJSON()"), folderActions, 'Sort keeps the same position and size across modes');
    assert.ok(await evaluate("!document.querySelector('.app-header #metadata-toggle') && document.getElementById('metadata-toggle').textContent === 'Info'"), 'Info is a named sidebar disclosure');
    await browser.openInfo();
    await waitFor("document.getElementById('metadata-panel').textContent.includes('1000 × 1800')");
    assert.ok(await evaluate("(() => { const path=document.querySelector('.metadata-path'), text=path.querySelector('.metadata-path-text'), facts=document.getElementById('metadata-facts'), copy=path.querySelector('.copy-path'); return path===document.getElementById('metadata-panel').firstElementChild && path.getBoundingClientRect().bottom <= facts.getBoundingClientRect().top && text.getBoundingClientRect().width===path.getBoundingClientRect().width && copy.getBoundingClientRect().right===path.getBoundingClientRect().right; })()"), 'The full path is first, with Copy beside it and no redundant heading');
    assert.deepEqual(await evaluate("[...document.querySelectorAll('.metadata-date')].map(row => ({label:row.previousElementSibling.textContent, date:!!row.querySelector('time').dateTime, age:!!row.querySelector('time').title}))"),
        [{label:'Modified', date:true, age:true}, {label:'Taken', date:true, age:true}], 'Modified and Taken share exact-date and relative-age rendering');
    assert.equal(await evaluate("[...document.querySelectorAll('.metadata-attributes dt')].find(row => row.textContent==='Taken').nextElementSibling.querySelector('time').dateTime"),
        '2024-03-14T12:30:00+05:30', 'Capture timezone survives extraction and date rendering');
    const location = await evaluate("(() => { const label=[...document.querySelectorAll('.metadata-attributes dt')].find(row => row.textContent==='Location'), link=label.nextElementSibling.querySelector('a'); return {value:link.textContent, href:link.href, target:link.target, rel:link.rel}; })()");
    assert.equal(location.value, '33.86000° S, 151.20000° E');
    assert.equal(new URL(location.href).searchParams.get('mlat'), '-33.86');
    assert.equal(location.target, '_blank', 'A map can be opened while keeping the reader in place');
    assert.equal(location.rel, 'noopener noreferrer');
    assert.deepEqual(await evaluate("({header:document.querySelector('.app-header').offsetHeight, canvas:document.getElementById('viewer-canvas').getBoundingClientRect().toJSON()})"), viewerFrame, 'Opening Info must not resize or move the viewer');
    assert.equal(await evaluate("document.querySelector('.app-header #metadata-toggle') === null"), true);
    assert.match(await evaluate("document.querySelector('#metadata-panel .copy-path').getAttribute('aria-label')"), /^(Copy full path|Copied)$/);
    assert.ok(await evaluate("!document.querySelector('#metadata-panel h2, .metadata-path-heading') && document.getElementById('metadata-panel').getAttribute('aria-labelledby') === 'metadata-toggle' && !document.getElementById('metadata-panel').hasAttribute('tabindex')"));
    await screenshot('image-metadata');
    await click('metadata-toggle');
    await click('metadata-toggle');
    await evaluate("window.sidebarInfo=document.querySelector('#metadata-toggle'); window.headerFolder=document.querySelector('#item-path a')");
    assert.equal(await evaluate("document.activeElement.id"), 'metadata-toggle');
    await nativeKey('ArrowRight', 39);
    await readyImage(second);
    assert.equal(await evaluate('document.activeElement.id'), 'metadata-toggle', 'Info keeps focus while reader arrows navigate');
    await nativeKey('ArrowLeft', 37);
    await readyImage(first);
    await evaluate("document.getElementById('viewer-canvas').focus()");
    await nativeKey('ArrowRight', 39);
    await readyImage(second);
    assert.ok(await evaluate("sidebarInfo===document.querySelector('#metadata-toggle') && headerFolder===document.querySelector('#item-path a')"),
        'Changing an image keeps header controls and folder breadcrumbs in place');
    await waitFor("document.querySelector('.metadata-path-text')?.textContent.endsWith('/page10.jpg') && document.querySelector('#metadata-panel .copy-path')");
    assert.deepEqual(await evaluate("document.querySelector('.sort-controls').getBoundingClientRect().toJSON()"), folderActions, 'Changing the current item must not move its controls');
    assert.equal(await evaluate("(!document.getElementById('folder-tree').hidden && document.getElementById('item-info').open)"), true);
    await evaluate("window.copiedPath=null; Object.defineProperty(navigator, 'clipboard', {configurable:true, value:{writeText:async text => { window.copiedPath=text; }}})");
    await waitFor("!document.getElementById('metadata-details').classList.contains('loading')");
    const copyBounds = await evaluate("document.querySelector('#metadata-panel .copy-path').getBoundingClientRect().toJSON()");
    for (const type of ['mousePressed', 'mouseReleased']) await call('Input.dispatchMouseEvent', {type, x:copyBounds.x+copyBounds.width/2, y:copyBounds.y+copyBounds.height/2, button:'left', clickCount:1});
    await waitFor('window.copiedPath');
    assert.equal(await evaluate('window.copiedPath'), absoluteRoot + '/' + second);
    assert.equal(await evaluate("(!document.getElementById('folder-tree').hidden && document.getElementById('item-info').open)"), true);
    const previousBounds = await evaluate("document.getElementById('viewer-prev').getBoundingClientRect().toJSON()");
    for (const type of ['mousePressed', 'mouseReleased']) await call('Input.dispatchMouseEvent', {type, x:previousBounds.x+previousBounds.width/2, y:previousBounds.y+previousBounds.height/2, button:'left', clickCount:1});
    await readyImage(first);
    await waitFor("document.querySelector('.metadata-path-text')?.textContent.endsWith('/page2.jpg')");
    assert.equal(await evaluate("(!document.getElementById('folder-tree').hidden && document.getElementById('item-info').open)"), true);
    await click('metadata-toggle');
    await waitFor("!document.getElementById('item-info').open");
    assert.equal(await evaluate("document.getElementById('viewer').hidden"), false);

    await readyImage(first);
    await screenshot('viewer');
    await click('viewer-next');
    await readyImage(second);
    await click('viewer-next');
    await readyImage(last);
    const heightAtEnd = await evaluate("document.getElementById('viewer-image').height");
    await click('viewer-next');
    await waitFor("document.getElementById('viewer-next').getAttribute('aria-label') === 'Go to first item'");
    assert.equal(await evaluate("document.getElementById('viewer-image').height"), heightAtEnd);
    assert.equal(await evaluate("document.getElementById('viewer-next').dataset.icon"), 'first', 'At the end, the arrow becomes an explicit return-to-first action');
    assert.equal(await evaluate("document.getElementById('viewer-next').textContent.trim()"), '');
    await screenshot('collection-boundary');
    await key('ArrowRight', true);
    assert.ok(await evaluate(imageIs(last)));
    await key('ArrowRight');
    await readyImage(first);
    assert.equal(await evaluate("document.getElementById('viewer-wrap')"), null);
    assert.equal(await evaluate("document.getElementById('viewer-next').dataset.icon"), 'next', 'Normal navigation icon returns after wrapping');

    // Edge gestures consume momentum; reverse wheel entry is at the previous image's bottom.
    await setZoom(150);
    await waitFor("new URLSearchParams(location.search).get('size') === '1.5'");
    assert.ok((await position()).max > 1000);
    await evaluate("document.getElementById('viewer-canvas').scrollTop = 400");
    await wheel(120);
    assert.ok((await position()).top > 400);
    assert.ok(await evaluate(imageIs(first)));
    await wheel(100000);
    assert.equal((await position()).top, (await position()).max);
    await wheel(70);
    await wheel(20);
    assert.ok(await evaluate(imageIs(first)));
    await pause(300);
    await wheel(100);
    await readyImage(second);
    assert.equal((await position()).top, 0);
    await wheel(20);
    assert.equal((await position()).top, 0);
    await pause(300);
    await wheel(-100);
    await readyImage(first);
    assert.ok(Math.abs((await position()).top - (await position()).max) <= 2);
    await click('viewer-next');
    await readyImage(second);
    await click('viewer-prev');
    await readyImage(first);
    assert.equal((await position()).top, 0);

    // Zoom preserves the source image point; manual sizing survives navigation and URLs.
    await evaluate("document.getElementById('viewer-canvas').scrollTop = 450");
    const sourcePoint = () => evaluate("(()=>{const c=document.getElementById('viewer-canvas'),i=document.getElementById('viewer-image'),b=c.getBoundingClientRect(),r=i.getBoundingClientRect();return (b.top+c.clientHeight/2-r.top)/(r.width/i.naturalWidth);})()");
    const beforeZoom = await sourcePoint();
    await click('viewer-zoom-in');
    assert.ok(Math.abs(await sourcePoint() - beforeZoom) < 3);
    await evaluate("document.getElementById('viewer-canvas').scrollLeft = 0");
    await call('Input.dispatchMouseEvent',{type:'mouseWheel',x:700,y:350,deltaX:120,deltaY:0});
    await pause(150);
    assert.ok(await evaluate("document.getElementById('viewer-canvas').scrollLeft > 0"));
    const size = await evaluate("(new URLSearchParams(location.search).get('size') || 'auto')");
    assert.equal(await evaluate("new URLSearchParams(location.search).get('size')"), size);
    await click('viewer-next');
    await readyImage(second);
    assert.equal(await evaluate("(new URLSearchParams(location.search).get('size') || 'auto')"), size);
    await evaluate("document.getElementById('viewer-stage').dispatchEvent(new WheelEvent('wheel',{deltaY:100,ctrlKey:true,cancelable:true}))");
    assert.ok(await evaluate(imageIs(second)));

    assert.equal(await evaluate("document.querySelector('[data-reading-layout=strip]').getAttribute('aria-current')"), 'page');
    await waitFor("document.querySelectorAll('#viewer-strip button').length === 3");
    assert.deepEqual(await evaluate("Array.from(document.querySelectorAll('#viewer-strip .folder-start .strip-folder'), node=>node.textContent)"), ['Chapter 1', 'Chapter 2/deep']);
    // Resize through the actual pointer handle, then the keyboard, without changing image.
    const resizePoint = await evaluate(`(() => { const r=document.querySelector('.strip-resizer').getBoundingClientRect(); return {x:r.x+r.width/2,y:r.y+r.height/2}; })()`);
    const thumbHeight = await evaluate("document.querySelector('#viewer-strip button').getBoundingClientRect().height");
    await call('Input.dispatchMouseEvent', {type:'mousePressed', button:'left', clickCount:1, ...resizePoint});
    await call('Input.dispatchMouseEvent', {type:'mouseMoved', button:'left', buttons:1, x:resizePoint.x, y:resizePoint.y-80});
    await call('Input.dispatchMouseEvent', {type:'mouseReleased', button:'left', clickCount:1, x:resizePoint.x, y:resizePoint.y-80});
    await waitFor(`document.querySelector('#viewer-strip button').getBoundingClientRect().height > ${thumbHeight + 70}`);
    await screenshot('strip-resized-chapters');
    await evaluate("document.querySelector('.strip-resizer').focus()");
    await call('Input.dispatchKeyEvent', {type:'keyDown', key:'ArrowDown', code:'ArrowDown', windowsVirtualKeyCode:40});
    await call('Input.dispatchKeyEvent', {type:'keyUp', key:'ArrowDown', code:'ArrowDown', windowsVirtualKeyCode:40});
    assert.equal(await evaluate("Number(document.querySelector('.strip-resizer').getAttribute('aria-valuenow'))"), thumbHeight + 64);
    assert.ok(await evaluate(imageIs(second)));
    assert.equal(await evaluate("sessionStorage.getItem('thumbnailSize')"), String(thumbHeight + 64));
    await evaluate("import('/gallery.js').then(({app})=>app.viewer.filmstrip.setSize(64))");
    await evaluate("sessionStorage.setItem('thumbnailSize','64'); document.getElementById('viewer-canvas').focus()");
    await waitFor("import('/gallery.js').then(({app})=>app.viewer.viewport.box.height === document.getElementById('viewer-canvas').clientHeight)");
    // Hidden filmstrip cancels preview work and does not request thumbnails on later pages.
    await evaluate("document.getElementById('viewer-canvas').scrollTop = 450");
    const beforeStrip = await sourcePoint();
    await presentation('single');
    assert.equal(await evaluate("new URLSearchParams(location.search).get('view')"), 'single');
    await pause(150);
    assert.ok(Math.abs(await sourcePoint() - beforeStrip) < 3);
    const thumbnailsBefore = requests.filter(url=>url.includes('/thumbnail?')).length;
    await click('viewer-next');
    await readyImage(last);
    await pause(300);
    assert.equal(requests.filter(url=>url.includes('/thumbnail?')).length, thumbnailsBefore);
    await key('Escape');
    await waitFor("document.getElementById('viewer').hidden");
    assert.ok(await evaluate("document.activeElement.getClientRects().length > 0"));

    // A temporary Overview visit retains only the current image's reading point.
    await browser.start(viewerUrl(first, '1.5'));
    await readyImage(first);
    await setZoom(150);
    await waitFor("import('/gallery.js').then(({app}) => app.viewer.viewport.box.height === app.viewer.canvas.clientHeight && !app.viewer.filmstrip.container.hidden)");
    await evaluate("document.getElementById('viewer-canvas').scrollTop = 700");
    const readingPoint = await sourcePoint();
    const readingUrl = await evaluate('location.href');
    await click('overview-folder');
    await waitFor("!document.getElementById('overview').hidden && document.querySelector('#overview .picture')");
    await click('read-strip');
    await readyImage(first);
    await pause(100);
    assert.ok(Math.abs(await sourcePoint() - readingPoint) < 3, 'View resumes the same passage after Overview');
    assert.equal(await evaluate('location.href'), readingUrl, 'Restoring coordinates does not change the URL');

    await click('overview-folder');
    await waitFor("!document.getElementById('overview').hidden");
    await evaluate('history.back()');
    await readyImage(first);
    await pause(100);
    assert.ok(Math.abs(await sourcePoint() - readingPoint) < 3, 'Back from Overview also resumes the passage');

    await click('overview-folder');
    await waitFor("!document.getElementById('overview').hidden");
    await call('Page.reload');
    await waitFor("!document.getElementById('overview').hidden && document.querySelector('#overview .picture')");
    await click('read-strip');
    await readyImage(first);
    await pause(100);
    assert.ok((await position()).top < 100, 'Reload clears the temporary reading point');

    await evaluate("document.getElementById('viewer-canvas').scrollTop = 700");
    await click('overview-folder');
    await waitFor(`document.querySelector('#overview [data-path="${second}"] .picture')`);
    await evaluate(`document.querySelector('#overview [data-path="${second}"] .picture').click()`);
    await readyImage(second);
    await pause(100);
    assert.ok((await position()).top < 100, 'Choosing another image starts at its normal entry point');

    await evaluate("document.getElementById('viewer-canvas').scrollTop = 700");
    await click('overview-folder');
    await waitFor("!document.getElementById('overview').hidden");
    await click('browse-folder');
    await waitFor("document.getElementById('viewer').hidden");
    await click('read-strip');
    await readyImage(second);
    await pause(100);
    assert.ok((await position()).top < 100, 'Entering Browse discards the temporary reading point');
    assert.ok((await position()).max > 1000, 'The reset is checked on an enlarged image');

    await evaluate("document.getElementById('viewer-canvas').scrollTop = 700");
    await click('overview-folder');
    await waitFor("!document.getElementById('overview').hidden");
    await click('folders-toggle');
    await waitFor("document.querySelector('.tree-row[data-path=\"Album\"] a')");
    await evaluate("document.querySelector('.tree-row[data-path=\"Album\"] a').click()");
    await waitFor("document.querySelector('.tree-row[data-path=\"Album/Chapter 2\"] a')");
    await evaluate("document.querySelector('.tree-row[data-path=\"Album/Chapter 2\"] a').click()");
    await waitFor(`document.querySelector('#overview [data-path="${last}"] .picture')`);
    assert.ok(await evaluate("!document.getElementById('overview').hidden"), 'Tree folder selection keeps Overview');
    await click('read-strip');
    await readyImage(last);
    await pause(100);
    assert.equal(await evaluate("new URLSearchParams(location.search).get('folder')"), 'Album/Chapter 2', 'View stays in the folder chosen through the tree');
    assert.ok((await position()).top < 100, 'Changing folders does not restore the previous reading point');
}
