import assert from 'node:assert/strict';
import {readState, stateUrl, ScreenMode, ImageSize} from '../../image_browser/web/static/state.js';

export async function run(browser, fixtures) {
    const {call, evaluate, waitFor, open, click, key, nativeKey, screenshot, readyImage, position, viewerUrl, presentation, setZoom, headerPositions} = browser;
    const {first, last} = fixtures;
    await browser.start();
    // Special filenames and narrow screens retain controls, full names, and a visible focus target.
    // Collection identity follows traversal, even when the URL's browsing folder differs.
    await open(stateUrl({...readState(''), mode:ScreenMode.VIEW, folder:'Album', collection:'Album/Chapter 2', image:last, filter:'Chapter'}));
    await readyImage(last);
    assert.equal(await evaluate("document.querySelector('#item-path .selected-folder').textContent"), 'Chapter 2');
    assert.equal(await evaluate("document.getElementById('overview-folder').title"), 'Collection overview');
    assert.equal(await evaluate("document.getElementById('overview-folder').getAttribute('aria-label')"), 'Collection overview');
    await click('overview-folder');
    await waitFor("!document.getElementById('overview').hidden");
    assert.equal(await evaluate("document.querySelector('#item-path .selected-folder').textContent"), 'Chapter 2');
    await click('read-strip');
    await readyImage(last);
    assert.equal(await evaluate("new URLSearchParams(location.search).get('folder')"), 'Album/Chapter 2');
    assert.equal(await evaluate("new URLSearchParams(location.search).get('collection')"), null);
    assert.equal(await evaluate("new URLSearchParams(location.search).get('filter')"), null, 'An old parent filter is not applied to the selected child collection');

    // Collapsed path ranges retain browsing context and file identity without overlapping.
    await call('Emulation.setDeviceMetricsOverride', {width:320,height:844,deviceScaleFactor:1,mobile:true});
    await open(viewerUrl(last));
    await readyImage(last);
    const beforePathLayout = await headerPositions();
    assert.ok(await evaluate(`(() => {
        const path=document.getElementById('item-path'), folder=path.querySelector('.selected-folder').getBoundingClientRect();
        const bounds=path.getBoundingClientRect(), name=path.querySelector('.item-name').getBoundingClientRect();
        return path.scrollWidth <= path.clientWidth+1 && folder.left >= bounds.left-.5 && folder.right <= name.left+.5 && name.right <= bounds.right+.5;
    })()`), 'The browsing folder and filename remain visible without scrolling or overlap');
    assert.equal(await evaluate("document.querySelectorAll('#item-path .breadcrumb-gap').length"), 1);
    assert.ok(await evaluate("[...document.querySelectorAll('#item-path a .breadcrumb-label')].every(label=>getComputedStyle(label).textDecorationLine.includes('underline'))"));
    assert.equal(await evaluate("document.querySelector('#item-path .item-name').getAttribute('aria-current')"), 'page');
    await evaluate("window.pathGap=document.querySelector('#item-path .breadcrumb-gap');pathGap.focus();pathGap.click()");
    await waitFor("document.querySelector('.breadcrumb-menu:popover-open a')");
    assert.deepEqual(await evaluate("[...document.querySelectorAll('.breadcrumb-menu:popover-open a')].map(link=>new URL(link.href).searchParams.get('folder'))"), [null, 'Album/Chapter 2', 'Album/Chapter 2/deep']);
    const menuEntry = await evaluate('location.href');
    for (const [key, code] of [['ArrowLeft', 37], ['ArrowUp', 38], ['ArrowRight', 39], ['ArrowDown', 40]]) await nativeKey(key, code);
    assert.equal(await evaluate('location.href'), menuEntry, 'Path keys do not turn images');
    await nativeKey('Escape', 27);
    assert.ok(await evaluate("!document.querySelector('.breadcrumb-menu:popover-open') && document.activeElement===pathGap && !document.getElementById('viewer').hidden"));
    await nativeKey('Enter', 13);
    await waitFor("document.querySelector('.breadcrumb-menu:popover-open a')");
    await nativeKey('Tab', 9);
    await nativeKey('Tab', 9);
    await nativeKey('Tab', 9);
    assert.equal(await evaluate('document.activeElement.id'), 'viewer-zoom-out');
    await nativeKey('Escape', 27);
    assert.ok(await evaluate("!document.querySelector('.breadcrumb-menu:popover-open') && document.activeElement===pathGap && !document.getElementById('viewer').hidden"), 'Escape dismisses the path menu after Tab moves outside it');
    await nativeKey('Enter', 13);
    await waitFor("document.querySelector('.breadcrumb-menu:popover-open a')");
    const middle = await browser.newTab('.breadcrumb-menu:popover-open li:nth-child(2) a');
    assert.equal(middle.get('folder'), 'Album/Chapter 2');
    assert.equal(middle.get('image'), null);
    const modified = await browser.newTab('.breadcrumb-menu:popover-open li:nth-child(2) a', 'left', 4);
    assert.equal(modified.get('folder'), 'Album/Chapter 2');
    await screenshot('breadcrumb-folders-mobile');
    await evaluate("document.querySelector('.breadcrumb-menu:popover-open li:last-child a').click()");
    await waitFor("document.getElementById('viewer').hidden && new URLSearchParams(location.search).get('folder')==='Album/Chapter 2/deep'");
    await evaluate('history.back()');
    await readyImage(last);
    assert.deepEqual(await headerPositions(), beforePathLayout);
    await screenshot('collapsed-path-mobile');
    assert.equal(beforePathLayout.height, 85);
    assert.deepEqual(beforePathLayout.modes.map(rect => [rect.width, rect.height]), [[32,32], [32,32], [40,32], [40,32], [40,32]]);
    const readingTools = await evaluate("[...document.querySelectorAll('#viewer-zoom-out, #viewer-zoom-in')].map(button => button.getBoundingClientRect().toJSON())");
    assert.ok(readingTools.every(rect => rect.x >= beforePathLayout.navigation.right && rect.right <= 320));
    await presentation('single');
    assert.deepEqual(await headerPositions(), beforePathLayout);
    assert.deepEqual(await evaluate("[...document.querySelectorAll('#viewer-zoom-out, #viewer-zoom-in')].map(button => button.getBoundingClientRect().toJSON())"), readingTools);
    await screenshot('mobile-320-image-only');
    await click('overview-folder');
    await waitFor("!document.getElementById('overview').hidden && document.querySelector('#overview .card')");
    assert.deepEqual(await headerPositions(), beforePathLayout, 'All navigation and item actions keep their anchors at 320px');
    assert.ok(await evaluate("document.querySelector('.viewer-tools').classList.contains('unavailable') && document.documentElement.scrollWidth <= innerWidth"));
    await screenshot('mobile-320-overview');
    await click('browse-folder');
    await waitFor("document.getElementById('viewer').hidden && document.querySelectorAll('.folder-card').length === 2");
    assert.deepEqual(await headerPositions(), beforePathLayout, 'Browse uses the same navigation, path and Info anchors');
    await screenshot('mobile-320-browse');
    const currentBrowseEntry = await evaluate('({url:location.href,length:history.length})');
    await click('browse-folder');
    assert.deepEqual(await evaluate('({url:location.href,length:history.length})'), currentBrowseEntry);
    await evaluate("window.browsingLink=document.querySelector('#item-path .selected-folder')");
    await call('Emulation.setDeviceMetricsOverride', {width:1440,height:900,deviceScaleFactor:1,mobile:false});
    await waitFor("!document.querySelector('#item-path .breadcrumb-gap')");
    assert.ok(await evaluate("browsingLink===document.querySelector('#item-path .selected-folder') && document.querySelector('#item-path a').textContent==='images'"), 'Resizing restores the full path using the same links');
    await open(viewerUrl('Odd & #/a ?#%.jpg', ImageSize.DEFAULT, 'Odd & #'));
    await readyImage('Odd & #/a ?#%.jpg');
    await call('Emulation.setDeviceMetricsOverride', {width:390,height:844,deviceScaleFactor:1,mobile:true});
    await open(viewerUrl(first,'1.5'));
    await readyImage(first);
    assert.ok(await evaluate('document.documentElement.scrollWidth <= innerWidth'));
    assert.equal(await evaluate("document.querySelector('#item-path .selected-folder').textContent"), 'Album');
    assert.ok(await evaluate("getComputedStyle(document.querySelector('#item-path .selected-folder .breadcrumb-label')).textDecorationLine.includes('underline')"));
    assert.ok(await evaluate("document.getElementById('browse-folder').getBoundingClientRect().right <= innerWidth"));
    assert.ok(await evaluate("document.querySelector('.app-header').getBoundingClientRect().height <= 85"));
    assert.ok(await evaluate("document.getElementById('browse-folder').scrollWidth <= document.getElementById('browse-folder').clientWidth"));
    await screenshot('mobile-viewer');
    const mobileModeAction = await evaluate("document.getElementById('read-strip').getBoundingClientRect().toJSON()");
    const mobileActions = await evaluate("document.getElementById('item-actions').getBoundingClientRect().toJSON()");
    const mobileFrame = await evaluate("document.getElementById('viewer-canvas').getBoundingClientRect().toJSON()");
    await evaluate("document.querySelector('#item-actions .item-info').click()");
    await waitFor("document.getElementById('metadata-details').textContent.includes('1000 × 1800')");
    assert.deepEqual(await evaluate("document.getElementById('viewer-canvas').getBoundingClientRect().toJSON()"), mobileFrame);
    assert.ok(await evaluate("(() => { const rect=document.getElementById('metadata-popover').getBoundingClientRect(); return rect.left >= 0 && rect.right <= innerWidth && rect.bottom <= innerHeight; })()"));
    assert.ok(await evaluate("document.getElementById('metadata-popover').getBoundingClientRect().top >= document.querySelector('.app-header').getBoundingClientRect().bottom"), 'Info must not obscure the location or filename');
    await screenshot('mobile-info');
    await evaluate("document.querySelector('#item-actions .item-info').click()");
    assert.equal(await evaluate("document.getElementById('metadata-popover').matches(':popover-open')"), false);
    await nativeKey('Tab', 9);
    assert.ok(await evaluate("document.activeElement.getClientRects().length > 0"));
    await open('/?folder=Names&compact=1');
    await waitFor("document.querySelector('.list-name')");
    assert.deepEqual(await evaluate("document.getElementById('read-strip').getBoundingClientRect().toJSON()"), mobileModeAction, 'View keeps identical geometry on narrow screens');
    assert.deepEqual(await evaluate("document.getElementById('item-actions').getBoundingClientRect().toJSON()"), mobileActions, 'The narrow layout uses the same action position in Browse and View');
    assert.ok(await evaluate("document.querySelector('.list-name').getBoundingClientRect().bottom <= document.querySelector('.list-item').getBoundingClientRect().bottom"));
    assert.ok(await evaluate("document.querySelector('.folder-view').getBoundingClientRect().right < document.querySelector('.list-name').getBoundingClientRect().left"));
    assert.equal(await evaluate("document.querySelector('.list-item').firstElementChild.className"),'folder-actions choice-group');
    await screenshot('long-names');
    await evaluate("document.querySelector('.list-name').click()");
    await waitFor("document.querySelector('#item-path .selected-folder').textContent.includes('Chapter 123')");
    await click('read-strip');
    await waitFor("document.querySelector('#item-path .item-name')?.textContent.includes('Harbour at sunrise')");
    assert.ok(await evaluate("(() => {const link=document.querySelector('#item-path .selected-folder'), label=link.querySelector('.breadcrumb-label'), path=document.getElementById('item-path'); return label.scrollWidth > label.clientWidth && link.title.includes('Chapter 123') && path.scrollWidth<=path.clientWidth+1;})()"), 'Long browsing-folder and file names truncate cleanly and retain their full tooltips');
    assert.ok(await evaluate("document.getElementById('browse-folder').getBoundingClientRect().right <= innerWidth"));
    assert.ok(await evaluate("document.querySelector('.app-header').getBoundingClientRect().height <= 85"));
    await screenshot('long-header');
    await evaluate("window.longFolder=document.querySelector('#item-path .selected-folder');longFolder.focus()");
    await evaluate("import('/gallery.js').then(({app}) => app.viewer.updateCollectionLabel())");
    assert.ok(await evaluate("longFolder===document.querySelector('#item-path .selected-folder') && document.activeElement===longFolder"), 'Refreshing controls preserves breadcrumb links and focus');
}
