import assert from 'node:assert/strict';
import {mkdirSync} from 'node:fs';
import {join} from 'node:path';
import {ScreenMode} from '../../image_browser/web/static/state.js';

export async function run(browser, {first, last, fixtureRoot}) {
    const {evaluate, waitFor, click, nativeKey, readyImage, requests, open, call, newTab, screenshot, setZoom} = browser;
    const row = path => '.tree-row[data-path=' + JSON.stringify(path) + ']';
    const activate = (path, selector = 'a') => evaluate(`document.querySelector(${JSON.stringify(row(path) + ' ' + selector)}).click()`);
    const pointerClick = async (path, clickCount = 1) => {
        const rect = await evaluate(`document.querySelector(${JSON.stringify(row(path) + ' a')}).getBoundingClientRect().toJSON()`);
        for (const type of ['mousePressed', 'mouseReleased']) {
            await call('Input.dispatchMouseEvent', {type, button: 'left', clickCount, x: rect.x + rect.width / 2, y: rect.y + rect.height / 2});
        }
    };
    const attach = () => evaluate("import('/gallery.js').then(({app}) => { window.treeApp=app; })");
    const expanded = () => evaluate('[...treeApp.tree.expanded].sort()');
    const folders = () => evaluate('treeApp.tree.rows.filter(row=>!row.status).map(row=>row.path)');
    const folderRequests = () => requests.filter(url => new URL(url).pathname === '/api/folder');

    await browser.start();
    await waitFor("document.querySelector('#grid .card') && document.getElementById('grid-viewport').getAttribute('aria-busy') === 'false'");
    await attach();
    assert.ok(await evaluate("document.getElementById('folder-tree').hidden"));
    await evaluate("window.sharedHeader=document.querySelector('.app-header'); window.sharedPane=document.getElementById('folder-tree'); window.sharedInfo=document.querySelector('.item-info'); window.sharedModes=[...document.querySelectorAll('[data-mode]')]");
    const header = await browser.headerPositions();
    const beforeOpen = folderRequests().length;
    await click('folders-toggle');
    await waitFor("document.querySelectorAll('.tree-row').length > 5 && document.activeElement.getAttribute('role') === 'treeitem'");
    assert.equal(folderRequests().length, beforeOpen, 'Opening reuses the listing already loaded by Browse');
    assert.ok(await evaluate("document.querySelectorAll('.mode-navigation').length === 1 && document.querySelectorAll('.app-header > .item-location .copy-path').length === 0 && document.querySelectorAll('#folder-tree').length === 1"));
    assert.ok(await evaluate("document.querySelectorAll('.tree-row > .icon').length === 0 && document.querySelectorAll('.tree-guide').length > 0"));
    assert.equal(await evaluate("getComputedStyle(document.getElementById('folders-toggle')).borderColor"), await evaluate("getComputedStyle(document.getElementById('layout-previews')).borderColor"), 'The open toggle uses the shared selection style');
    assert.ok(await evaluate(`Boolean(document.querySelector(${JSON.stringify(row('Empty') + ' button')}))`), 'Unknown folders start with arrows');
    const emptyName = await evaluate(`document.querySelector(${JSON.stringify(row('Empty') + ' a')}).getBoundingClientRect().toJSON()`);
    const browseUrl = await evaluate('location.href');
    await activate('Empty', 'button');
    await waitFor(`!document.querySelector(${JSON.stringify(row('Empty') + ' button')})`);
    assert.equal(await evaluate('location.href'), browseUrl, 'Expanding a leaf does not navigate');
    assert.deepEqual(await evaluate(`document.querySelector(${JSON.stringify(row('Empty') + ' a')}).getBoundingClientRect().toJSON()`), emptyName, 'Removing an arrow keeps the name aligned');
    await activate('Single');
    await waitFor("treeApp.state.folder === 'Single' && !treeApp.grid.loadingFolder");
    assert.ok(await evaluate(`!document.querySelector(${JSON.stringify(row('Single') + ' button')})`), 'Selection also discovers leaves');
    await activate('Album');
    await waitFor("treeApp.state.folder === 'Album' && !treeApp.grid.loadingFolder");
    assert.ok(!(await folders()).includes('Album/Chapter 1'), 'Selection leaves the branch collapsed');
    const beforeExpand = folderRequests().length;
    const selectedUrl = await evaluate('location.href');
    await activate('Album');
    await waitFor(`document.querySelector(${JSON.stringify(row('Album/Chapter 1') + ' a')})`);
    assert.equal(folderRequests().length, beforeExpand, 'Expansion reuses the selected folder listing');
    assert.equal(await evaluate('location.href'), selectedUrl, 'Clicking the selected folder expands without navigating');
    await activate('Album');
    assert.ok(!(await expanded()).includes('Album'), 'Clicking the selected folder again collapses the peeked branch');
    assert.equal(await evaluate('location.href'), selectedUrl, 'Collapsing the selected folder keeps the current location');
    await activate('Single');
    await waitFor("treeApp.state.folder === 'Single' && !treeApp.grid.loadingFolder");
    await pointerClick('Album');
    assert.equal(await evaluate('treeApp.state.folder'), 'Album');
    assert.ok(!(await expanded()).includes('Album'), 'The first click selects without expanding');
    const selectedHistory = await call('Page.getNavigationHistory');
    await pointerClick('Album', 2);
    await waitFor(`document.querySelector(${JSON.stringify(row('Album/Chapter 1') + ' a')})`);
    assert.deepEqual((await call('Page.getNavigationHistory')).entries.map(entry => entry.id),
        selectedHistory.entries.map(entry => entry.id), 'The second click expands without another navigation entry');
    await activate('Single');
    await waitFor("treeApp.state.folder === 'Single' && !treeApp.grid.loadingFolder");
    await pointerClick('Album');
    await pointerClick('Album', 2);
    assert.ok((await expanded()).includes('Album'), 'Double-clicking an expanded unselected folder keeps its children visible');
    const branches = await expanded(), visible = await folders();
    await activate('Album/Chapter 1');
    await waitFor("treeApp.state.folder === 'Album/Chapter 1' && !treeApp.grid.loadingFolder");
    await activate('Album/Chapter 2');
    await waitFor("treeApp.state.folder === 'Album/Chapter 2' && !treeApp.grid.loadingFolder");
    assert.deepEqual(await expanded(), branches, 'Sibling selection preserves expansion');
    assert.deepEqual(await folders(), visible, 'Sibling selection does not add descendants');
    await nativeKey('c', 67);
    assert.equal(await evaluate('document.activeElement.closest(".tree-row").dataset.path'), 'Album/Chapter 1', 'Typeahead only moves tree focus');
    assert.equal(await evaluate('treeApp.state.folder'), 'Album/Chapter 2');
    await nativeKey('Enter', 13);
    await waitFor("treeApp.state.folder === 'Album/Chapter 1' && !treeApp.grid.loadingFolder");
    await screenshot('tree-browse');

    await click('read-strip');
    await readyImage(first);
    assert.equal(await evaluate('treeApp.state.mode'), ScreenMode.VIEW);
    assert.ok(await evaluate("!sharedPane.hidden && sharedPane === document.getElementById('folder-tree') && sharedHeader === document.querySelector('.app-header') && sharedInfo === document.querySelector('.item-info') && sharedModes.every(node=>node.isConnected)"));
    assert.deepEqual(await browser.headerPositions(), header, 'The shared header keeps its geometry in View');
    const modified = await newTab(row('Album/Chapter 2') + ' a');
    assert.equal(modified.get('folder'), 'Album/Chapter 2');
    assert.equal(modified.get('viewer'), '1');
    assert.equal((await newTab(row('Album/Chapter 2') + ' a', 'left', 4)).get('folder'), 'Album/Chapter 2');
    await evaluate("document.getElementById('viewer-canvas').focus()");
    await setZoom(150);
    await activate('Album/Chapter 2');
    await readyImage(last);
    assert.equal(await evaluate('treeApp.state.size'), '1.5');
    assert.equal(await evaluate("document.querySelector('#folder-tree [aria-current=page]').closest('.tree-row').dataset.path"), 'Album/Chapter 2', 'The tree marks the collection, not the image-containing folder');
    assert.deepEqual(await expanded(), branches);
    await screenshot('tree-view');
    assert.equal((await newTab('#browse-folder')).get('folder'), 'Album/Chapter 2', 'The Browse link targets the current collection');
    await click('browse-folder');
    await waitFor("treeApp.state.mode === 'browse' && !treeApp.grid.loadingFolder");
    assert.equal(await evaluate('treeApp.state.folder'), 'Album/Chapter 2', 'Browse stays in the folder selected through the tree');
    await evaluate('history.back()');
    await readyImage(last);
    assert.equal(await evaluate('treeApp.state.collection'), 'Album/Chapter 2', 'Back reverses the adjacent mode switch');
    await evaluate('history.back()');
    await readyImage(first);
    assert.equal(await evaluate('treeApp.state.collection'), 'Album/Chapter 1', 'Another Back reverses the folder selection');
    await evaluate('history.forward()');
    await readyImage(last);
    await evaluate('history.forward()');
    await waitFor("treeApp.state.mode === 'browse' && !treeApp.grid.loadingFolder");
    assert.equal(await evaluate('treeApp.state.folder'), 'Album/Chapter 2', 'Forward restores the corresponding location and mode');
    assert.deepEqual(await expanded(), branches, 'History navigation preserves deliberate tree expansion');
    await click('read-strip');
    await readyImage(last);
    assert.equal(await evaluate('treeApp.state.collection'), 'Album/Chapter 2', 'View stays in the same folder');
    await click('overview-folder');
    await waitFor("treeApp.state.mode === 'overview' && !treeApp.grid.loadingFolder");
    await activate('Album/Chapter 1');
    await waitFor("treeApp.state.collection === 'Album/Chapter 1' && !treeApp.grid.loadingFolder");
    assert.equal(await evaluate('treeApp.state.mode'), ScreenMode.OVERVIEW);
    await click('read-strip');
    await readyImage(first);
    await evaluate("document.getElementById('viewer-canvas').scrollTop=(document.getElementById('viewer-canvas').scrollHeight-document.getElementById('viewer-canvas').clientHeight)/2; window.inspectedPoint=treeApp.viewer.viewport.point(); treeApp.tree.focusRow('Album/Chapter 1')");
    await nativeKey('Escape', 27);
    assert.ok(await evaluate("sharedPane.hidden && treeApp.state.mode === 'view' && document.activeElement.id === 'folders-toggle'"), 'Escape from the tree closes only the panel');
    await waitFor("treeApp.viewer.viewport.box.width === document.getElementById('viewer-canvas').clientWidth");
    assert.ok(await evaluate('Math.abs(inspectedPoint.y-treeApp.viewer.viewport.point().y)<2'), 'Closing preserves the inspected image point');
    await click('folders-toggle');
    await activate('Album', 'button');
    const collapsed = await expanded();
    await click('folders-toggle');
    await click('folders-toggle');
    assert.deepEqual(await expanded(), collapsed, 'Reopening does not reveal collapsed ancestors');
    assert.equal(await evaluate('document.activeElement.closest(".tree-row").dataset.path'), 'Album');
    await evaluate("document.getElementById('viewer-canvas').focus()");
    await nativeKey('Escape', 27);
    await waitFor("treeApp.state.mode === 'browse' && !treeApp.grid.loadingFolder");
    assert.equal(await evaluate('treeApp.state.folder'), 'Album/Chapter 1', 'Escape switches to Browse in the current collection');
    assert.ok(await evaluate('!sharedPane.hidden'), 'Returning from the image keeps the docked panel open');

    // A local read failure retains its arrow and retries without changing the task.
    await browser.start();
    await attach();
    await waitFor('!treeApp.grid.loadingFolder');
    await click('folders-toggle');
    await waitFor(`document.querySelector(${JSON.stringify(row('Names') + ' button')})`);
    await call('Fetch.enable', {patterns: [{urlPattern: '*/api/folder*'}]});
    browser.network.folders = true;
    await activate('Names', 'button');
    await waitFor('treeApp.tree.pending.has("Names")');
    for (let attempt = 0; !browser.held.length && attempt < 160; attempt++) await browser.pause(50);
    assert.ok(browser.held.length, 'The failed folder request is held');
    const requestsDuringExpansion = folderRequests().length;
    await activate('Names', 'button');
    assert.ok(!(await expanded()).includes('Names'), 'A loading branch can be collapsed');
    await activate('Names', 'button');
    assert.equal(folderRequests().length, requestsDuringExpansion, 'Reopening a loading branch reuses its request');
    await call('Fetch.fulfillRequest', {requestId: browser.held.shift(), responseCode: 404,
        responseHeaders: [{name: 'Content-Type', value: 'application/json'}], body: Buffer.from('{"error":"Unreadable"}').toString('base64')});
    await waitFor('treeApp.tree.errors.has("Names")');
    assert.ok(await evaluate(`Boolean(document.querySelector(${JSON.stringify(row('Names') + ' button')}))`));
    await call('Fetch.disable'); browser.network.folders = false;
    await evaluate("document.querySelector('.tree-status[data-path=Names] .tree-retry').click()");
    await waitFor('treeApp.tree.listings.has("Names") && !treeApp.tree.pending.size');
    assert.equal(await evaluate('treeApp.state.folder'), '');
    await evaluate("treeApp.tree.toggleBranch('Mixed'); treeApp.tree.setOpen(false)");
    assert.ok(await evaluate("treeApp.tree.expanded.has('Mixed') && !treeApp.tree.pending.size"), 'Hiding cancels tree requests while preserving expansion');
    await click('folders-toggle');
    await waitFor('treeApp.tree.listings.has("Mixed") && !treeApp.tree.pending.size');
    await activate('Packed.cbz', 'button');
    await waitFor(`document.querySelector(${JSON.stringify(row('Packed.cbz/Chapter 3') + ' a')})`);
    assert.ok((await folders()).includes('Packed.cbz/Chapter 3') && !(await folders()).some(path => path.endsWith('.jpg')), 'Archive branches show folders, never member files');
    await activate('Packed.cbz/Chapter 3');
    await waitFor("treeApp.state.folder === 'Packed.cbz/Chapter 3' && !treeApp.grid.loadingFolder");
    assert.ok(await evaluate(`!document.querySelector(${JSON.stringify(row('Packed.cbz/Chapter 3') + ' button')})`));

    await open('/?folder=Packed.cbz%2FChapter+3');
    await attach();
    await waitFor(`document.querySelector(${JSON.stringify(row('Packed.cbz/Chapter 3') + ' a[aria-current=page]')})`);
    assert.deepEqual(await expanded(), ['', 'Packed.cbz'], 'A bookmarked folder reveals its ancestors without opening its children');

    // Thousands of siblings use a small DOM and retain scroll and focus when hidden.
    const large = join(fixtureRoot, 'Tree test');
    for (let index = 0; index < 2400; index++) mkdirSync(join(large, 'Folder ' + index), {recursive: true});
    await evaluate("import('/static/api.js').then(({refreshScope})=>refreshScope(''))");
    await open('/?folder=Tree+test&compact=1');
    await attach();
    await waitFor('!treeApp.grid.loadingFolder');
    assert.ok(await evaluate('!treeApp.tree.pane.hidden'), 'Desktop visibility survives a page load');
    await waitFor(`document.querySelector(${JSON.stringify(row('Tree test') + ' button')})`);
    await activate('Tree test', 'button');
    await waitFor('treeApp.tree.rows.length > 2400');
    const countBeforeScroll = folderRequests().length;
    await evaluate('treeApp.tree.pane.scrollTop=40000');
    await waitFor("document.querySelector('.tree-row[data-path=\"Tree test/Folder 1250\"]')");
    assert.ok(await evaluate("document.querySelectorAll('#folder-tree li').length < 45"), 'The tree mounts only visible rows and one focused row');
    assert.equal(folderRequests().length, countBeforeScroll, 'Scrolling does not inspect child folders');
    await evaluate("document.querySelector('.tree-row[data-path=\"Tree test/Folder 1250\"] a').focus()");
    assert.equal(await evaluate('treeApp.tree.focused'), 'Tree test/Folder 1250');
    const scroll = await evaluate('treeApp.tree.pane.scrollTop');
    await click('folders-toggle'); await click('folders-toggle');
    assert.equal(await evaluate('treeApp.tree.pane.scrollTop'), scroll, 'Reopening restores tree scroll');
    assert.equal(await evaluate('document.activeElement.closest(".tree-row").dataset.path'), 'Tree test/Folder 1250', 'Reopening restores tree focus');
    await nativeKey('End', 35);
    assert.equal(await evaluate('document.activeElement.closest(".tree-row").dataset.path'), 'Tree test/Folder 2399', 'Keyboard navigation reaches an unmounted row');
    await screenshot('tree-large');

    // Narrow navigation overlays the image and dismisses without an extra mode.
    await call('Emulation.setDeviceMetricsOverride', {width: 320, height: 844, deviceScaleFactor: 1, mobile: true});
    await open(browser.viewerUrl(first));
    await attach(); await readyImage(first);
    assert.ok(await evaluate('treeApp.tree.pane.hidden'), 'A narrow page starts with the tree closed');
    const canvas = await evaluate("document.getElementById('viewer-canvas').getBoundingClientRect().toJSON()");
    const mobileUrl = await evaluate('location.href');
    await click('folders-toggle');
    await waitFor('document.activeElement.getAttribute("role") === "treeitem"');
    assert.deepEqual(await evaluate("document.getElementById('viewer-canvas').getBoundingClientRect().toJSON()"), canvas);
    assert.equal(await evaluate("document.querySelector('.app-header').offsetHeight"), 85);
    assert.ok(await evaluate('document.documentElement.scrollWidth <= innerWidth'));
    await screenshot('tree-narrow');
    await activate('Album');
    await waitFor(`document.querySelector(${JSON.stringify(row('Album/Chapter 2') + ' a')})`);
    assert.ok(await evaluate('!treeApp.tree.pane.hidden'), 'The selected folder expands without dismissing the narrow tree');
    assert.equal(await evaluate('location.href'), mobileUrl, 'Expanding the selected folder does not navigate or restart reading');
    await readyImage(first);
    await activate('Album');
    assert.ok(await evaluate("!treeApp.tree.pane.hidden && !treeApp.tree.expanded.has('Album')"), 'The selected name collapses the peeked branch while keeping the narrow panel open');
    assert.equal(await evaluate('location.href'), mobileUrl);
    await readyImage(first);
    await click('folders-toggle');
    assert.equal(await evaluate('document.activeElement.id'), 'folders-toggle');
    await evaluate("document.querySelector('.item-info').click()");
    await waitFor("document.getElementById('metadata-popover').matches(':popover-open')");
    await click('folders-toggle');
    assert.ok(await evaluate("!treeApp.tree.pane.hidden && !document.getElementById('metadata-popover').matches(':popover-open')"));
    await evaluate("document.querySelector('.item-info').click()");
    assert.ok(await evaluate("treeApp.tree.pane.hidden && document.getElementById('metadata-popover').matches(':popover-open')"), 'Transient panels replace each other in either direction');
    await nativeKey('Escape', 27);
    await click('folders-toggle');
    await activate('Album');
    await waitFor(`document.querySelector(${JSON.stringify(row('Album/Chapter 2') + ' a')})`);
    assert.ok(await evaluate('!treeApp.tree.pane.hidden'), 'Toggling the selected name keeps the narrow overlay open');
    await activate('Album/Chapter 2');
    await readyImage(last);
    assert.ok(await evaluate('treeApp.tree.pane.hidden && treeApp.state.mode === "view"'));
    await click('folders-toggle');
    await nativeKey('Escape', 27);
    assert.ok(await evaluate('treeApp.tree.pane.hidden && treeApp.state.mode === "view"'));
    await click('folders-toggle');
    // The shared header's View control is outside the overlay and must remain usable.
    await click('overview-folder');
    await waitFor('treeApp.state.mode === "overview" && treeApp.tree.pane.hidden');
    assert.ok(await evaluate('treeApp.tree.pane.hidden'), 'An outside control dismisses the overlay and performs its action');
}
